### ISSUE TITLE
Display issues on OS X 10.9.2 / Java 2013-005 (11m4609)

### ISSUE THREAD

**Issue by rae** [TrsstProject/trsst#14]
Cannot log in. UI is not displayed correctly.
![screenshot 2014-04-17 11 47 26](https://cloud.githubusercontent.com/assets/5145/2736225/451c6762-c66a-11e3-9890-5a6b19f5bf25.jpg)

**Comment by albill** [comment]
Same here on my OS X 10.9.2 system.

**Comment by mmpowers** [comment]
Hmmm, are you guys on Retina displays, perchance?  

As a workaround for now, you can launch the command-line client with "serve --api" and connect with your browser of choice, which is frankly going to be a much better browser than our built-in one.

**Comment by albill** [comment]
Yes, retina.

**Comment by rae** [comment]
Yes, I have a retina display.

**Comment by rae** [comment]
Tried to use the command line, but got an error about version numbers:

```
$ pushd /Applications/trsst-client-0.2-SNAPSHOT.app/Contents
$ java -jar Java/trsst-client-0.2-SNAPSHOT-jfx.jar serve --gui
Apr 22, 2014 6:17:37 PM com.trsst.Common getBuildDate
WARNING: Could not parse build timestamp: null
Apr 22, 2014 6:17:37 PM com.trsst.Command doBegin
SEVERE: Unexpected error: java.lang.UnsupportedClassVersionError: org/eclipse/jetty/server/Handler : Unsupported major.minor version 51.0
java.lang.UnsupportedClassVersionError: org/eclipse/jetty/server/Handler : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at com.trsst.Command.doServe(Command.java:673)
    at com.trsst.Command.doBegin(Command.java:458)
    at com.trsst.Command.main(Command.java:191)
```

**Comment by rae** [comment]
Ditto with "serve --api"

**Comment by mmpowers** [comment]
Definitely JRE 1.8 is required.  We include it embedded in our distribution, but to build or run separately, you'll need to get the latest from Oracle (which is kind of a PITA).
