### ISSUE TITLE
document minimal JDK version for java standalone release

### ISSUE THREAD

**Issue by nhoening** [TrsstProject/trsst#18]
I get a java.lang.UnsupportedClassVersionError (see below), which usually happens because of a higher JDK during compile time and lower JDK during runtime.
My java is a default java on OSX 10.6.something and probably way too low. It would be good to know what Java JDK people need.

```
java.lang.UnsupportedClassVersionError: org/eclipse/jetty/server/Handler : Unsupported major.minor version 51.0
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
at com.trsst.Command.doServe(Command.java:673)
at com.trsst.Command.doBegin(Command.java:458)
at com.trsst.Command.main(Command.java:191)
```

**Comment by mmpowers** [comment]
Yes, required JRE is 1.8 which we ship with the client, but needs to be more clear on the site.
